# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-02 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='number_of_attendees',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
