# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-03 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='events',
        ),
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='events.Attendee'),
            preserve_default=False,
        ),
    ]
